apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: datagrid-usersession
  annotations:
    infinispan.org/monitoring: 'true'
  labels:
    com.redhat.component-name: Data_Grid
    com.redhat.component-type: application
    com.redhat.component-version: 8.3.1
    com.redhat.product-name: Red_Hat_Runtimes
    com.redhat.product-version: 2022-Q2
spec:
  replicas: 2
  service:
    type: DataGrid
    container:
      ephemeralStorage: true
  container:
    extraJvmOpts: -Xlog:gc*:stdout:time,level,tags
    memory: 1Gi
  security:
    endpointEncryption:
      type: None
    endpointAuthentication: false
    authorization:
      enabled: false
